version: '3'

services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage

  backend:
    image: backend:latest
    container_name: backend
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
    environment:
      - DATABASE_URL=postgresql://cv-api:cv-api@db/cv_api_dev
    depends_on:
      - redis
    links:
      - redis

  db:
    container_name: postgresql_db
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=cv-api
      - POSTGRES_PASSWORD=cv-api
      - POSTGRES_DB=cv_api_dev

  redis:
    container_name: redis-db
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  task_worker:
    container_name: redis-worker
    image: backend:latest
    command: rq worker --url redis://redis:6379 inference
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./storage:/storage
      - ./backend/models:/models
      - ./backend/api/:/api
      - ./backend/database/:/database
    environment:
      - DATABASE_URL=postgresql://cv-api:cv-api@db/cv_api_dev

  dashboard:
    build: dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    depends_on:
      - redis

volumes:
  postgres_data: